[terminal.shell]
program = "/usr/bin/zsh"
args = ["-l"]

[window]
opacity = 0.9
blur = false

[general]
live_config_reload = true
import = [
 "~/.config/alacritty/catppuccin-mocha.toml"
]

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 12

[selection]
save_to_clipboard = true
