[colors.primary]
background = '#231c1a'
foreground = '#f3f2f2'

[colors.cursor]
text = '#231c1a'
cursor = '#f3f2f2'

[colors.vi_mode_cursor]
text = '#231c1a'
cursor = '#c1978b'

[colors.search.matches]
foreground = '#302521'
background = '#a7b37f'

[colors.search.focused_match]
foreground = '#302521'
background = '#c1978b'

[colors.footer_bar]
foreground = '#302521'
background = '#e7e5e4'

[colors.hints.start]
foreground = '#302521'
background = '#b3a57f'

[colors.hints.end]
foreground = '#302521'
background = '#b3a57f'

[colors.selection]
text = '#b6b0af'
background = '#302521'


[colors.normal]
black   = '#302521'
red     = '#b6754d'
green   = '#c1978b'
yellow  = '#b3a57f'
blue    = '#a7b37f'
magenta = '#d3b5ac'
cyan    = '#d0c7af'
white   = '#f3f2f2'


[colors.bright]
black   = '#726662'
red     = '#b6754d'
green   = '#c1978b'
yellow  = '#b3a57f'
blue    = '#a7b37f'
magenta = '#d3b5ac'
cyan    = '#d0c7af'
white   = '#f3f2f2'


[colors.dim]
black   = '#302521'
red     = '#b6754d'
green   = '#c1978b'
yellow  = '#b3a57f'
blue    = '#a7b37f'
magenta = '#d3b5ac'
cyan    = '#d0c7af'
white   = '#f3f2f2'
