# Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more
bind = $mainMod, Return, exec, alacritty
bind = $mainMod, Q, killactive, 
bind = $mainMod, E, exec, dolphin
bind = $mainMod, space, togglefloating, 
bind = $mainMod, D, exec, rofi -show drun
bind = $mainMod SHIFT, P, toggleswallow, # dwindle
bind = $mainMod SHIFT, T, togglesplit, # dwindle
bind = $mainMod, F, fullscreen 
bind = $mainMod, Tab, workspace,previous
bind = $mainMod, W, exec, ~/.config/scripts/wal.sh

bind = $mainMod ALT, L, exec, hyprlock

bindd = $mainMod SHIFT, D, Discord, exec, discord
bindd = $mainMod SHIFT, W, Firefox, exec, firefox

# Move focus with mainMod + arrow keys
bind = $mainMod, h, movefocus, l
bind = $mainMod, l, movefocus, r
bind = $mainMod, k, movefocus, u
bind = $mainMod, j, movefocus, d

# Resize with mainMod + Alt + arrow keys
bind = SUPER ALT, left, resizeactive, -50 0
bind = SUPER ALT, right, resizeactive, 50 0
bind = SUPER ALT, up, resizeactive, 0 -50
bind = SUPER ALT, down, resizeactive, 0 50

# Switch workspaces with mainMod + [0-9]
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

# Move windows with mainMod + Shift + arrow keys
bind = SUPER SHIFT, h, movewindow, l
bind = SUPER SHIFT, l, movewindow, r
bind = SUPER SHIFT, k, movewindow, u
bind = SUPER SHIFT, j, movewindow, d

# Move active window to a workspace with mainMod + SHIFT + [0-9]
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9
bind = $mainMod SHIFT, 0, movetoworkspace, 10

# Scroll through existing workspaces with mainMod + scroll
bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1

# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow


# Brightness and Volume
bind = ,XF86AudioRaiseVolume, exec, amixer set Master 5%+
bind = ,XF86AudioLowerVolume, exec, amixer set Master 5%-
bind = ,XF86MonBrightnessUp, exec, brightnessctl s 2400+
bind = ,XF86MonBrightnessDown, exec, brightnessctl s 2400-
bind = ,XF86AudioMute, exec, amixer set Master toggle

# Screenshot
bind = $mainMod SHIFT, A, exec, hyprshot -m region -z --clipboard-only


# Shutdown
bind = SUPERSHIFT, Delete, exec, /home/enzom/.config/rofi/powermenu.sh

# Player Control
bind = , XF86AudioPrev, exec, playerctl previous
bind = , XF86AudioNext, exec, playerctl next
bind = , XF86AudioPlay, exec, playerctl play-pause

# Notification Shits
bind = SUPERSHIFT, grave, exec, dunstctl history-pop
bind = SUPERSHIFT, Return, exec, dunstctl context

bind = , page_down, pass, class:(discord)
bind = , page_up, pass, class:(discord)


# Togglea el workspace especial magic
bind = $mainMod, S, togglespecialworkspace, magic


bind = $mainMod, g, togglegroup
bind = ALT, tab, changegroupactive

bind = $mainMod SHIFT, R, exec, hyprctl reload
