color0 #273022
color1 #fd4663
color2 #9ec18b
color3 #8cb992
color4 #90b5a8
color5 #bad3ac
color6 #afd0b3
color7 #f2f3f2
color8 #646e5e
color9 #fd4663
color10 #9ec18b
color11 #8cb992
color12 #90b5a8
color13 #bad3ac
color14 #afd0b3
color15 #f2f3f2

cursor                #f2f3f2
cursor_text_color     #1d231a
background            #1d231a
foreground            #f2f3f2
selection_foreground  #b1b6af
selection_background  #273022
active_border_color   #9ec18b
inactive_border_color #273022
url_color             #9ec18b

active_tab_foreground   #1e221b
active_tab_background   #9ec18b
inactive_tab_foreground #b1b6af
inactive_tab_background #273022
cursor_trail_color      #b1b6af
