color0 #302521
color1 #b6754d
color2 #c1978b
color3 #b3a57f
color4 #a7b37f
color5 #d3b5ac
color6 #d0c7af
color7 #f3f2f2
color8 #726662
color9 #b6754d
color10 #c1978b
color11 #b3a57f
color12 #a7b37f
color13 #d3b5ac
color14 #d0c7af
color15 #f3f2f2

cursor                #f3f2f2
cursor_text_color     #231c1a
background            #231c1a
foreground            #f3f2f2
selection_foreground  #b6b0af
selection_background  #302521
active_border_color   #c1978b
inactive_border_color #302521
url_color             #c1978b

active_tab_foreground   #221d1b
active_tab_background   #c1978b
inactive_tab_foreground #b6b0af
inactive_tab_background #302521
cursor_trail_color      #b6b0af
